### ISSUE TITLE
Replace ComposeThread

### ISSUE THREAD

**Issue by Ashoat** [CommE2E/comm#118]
One common issues alpha testers have reported with the app is that it's too easy to accidentally create a thread that already exists. I tried to solve this with the "existing threads" panel in `ComposeThread`, but I think we'll need to fundamentally rethink this, because most people still miss it.

I think I like what Facebook Messenger does. When you hit the compose button, it pops up a modal with a `TagInput` at the top. As you add users to the `TagInput`, the area in the modal below the `TagInput` becomes a `MessageList`. If a thread with the users you've selected already exists, that thread's `MessageList` is displayed. If there is no such thread yet, it effectively shows what we call a "pending" thread, which gets created as soon as you send the first message.

**Comment by palys-swm** [comment]
Clicking new thread button should open a thread composer.
Thread composer on Android should be displayed as a full-width modal, with content that initially is slightly smaller and then grows to fill all the available space.
https://drive.google.com/file/d/18e-sIYrGS_A0QK3BXBOqeTXmnpdu4Mow/view?usp=sharing

Thread composer on iOS should be displayed as full-width modal, which is displayed above the rest of the app. The modal should not take the whole vertical space: there should be a gap at the top and the rest of the app (with slightly reduced size) should be displayed beneath it. Modal should appear from the bottom, and main app screen should shrink and move down, below the status bar.
![130268436_922993835109352_5573607962078342828_n](https://user-images.githubusercontent.com/54851691/101787371-4c883b00-3aff-11eb-81ce-04c68f6eecd3.png)

Thread composer should consist of user search component and message list.
User search component allows searching for users and selecting multiple entries - just like in friend / block list.
When a thread with exactly the same set of members, as selected in the search component, exists, then it should be displayed, otherwise a pending thread should be displayed. 
Sending a message in a pending thread should create a real thread.
Sending a message in any thread should open it in a usual way (outside the thread composer).

Open questions:
What should we do if there are couple of matching threads? We can probably display a list of them.
On iOS selecting users is achieved by a checklist, but I guess we should use the same approach as on Android (like tag input).
On iOS the thread was displayed only after selecting users and clicking done (tested on iPhone 8), but I think we should display a message list instead, just like on Android.

Tasks:
1. Create a modal (we can split this task by OS)
2. Create a thread composer component with search component
3. Modify message list so that it can be displayed inside the composer
4. Display the list in the composer
5. Handle sending a message: send a message and open list view outside the modal
6. Handle sending a message: create a real thread
7. Open thread composer after clicking new thread button
8. Remove old thread composer

**Comment by Ashoat** [comment]
Some thoughts:

1. I don't have permissions to see the Google Drive link you sent. In the future, if you want to embed a video into a GitHub comment, you can convert it to an animated GIF and then embed the GIF. But might be too much work for you.
2. We don't need to match the individual platform behavior 100%. For simplicity we can pick the same approach for iOS/Android. Unless React Navigation makes it easy to match the platform behavior, in which case we might as well.
3. It's worth noting that the "user search component" should display iff (a) the tag list is empty, or (b) the text input is non-empty.
4. Let's make sure we only "autocomplete" threads that don't have parent threads.
5. > What should we do if there are couple of matching threads? We can probably display a list of them.
    
    Hmm, displaying a list of matching threads seems like it will be challenging in terms of UX. At a higher level, our approach here should make it unlikely that there are multiple matching threads going forward, since the UI will make it impossible to create a second matching thread if one already exists. So if there are multiple matching threads, I think we can simply select the oldest one.
6. > On iOS selecting users is achieved by a checklist, but I guess we should use the same approach as on Android (like tag input).

    For some reason the experience you're seeing in Messenger on iOS is a bit different from what I'm seeing. I see a tag input without checkboxes. Let's definitely plan on taking the tag input approach, without any checkboxes.
7. > On iOS the thread was displayed only after selecting users and clicking done (tested on iPhone 8), but I think we should display a message list instead, just like on Android.
    
    I agree, and also worth noting that on my iPhone, Messenger doesn't have a "done" button. It seems to work like how you're describing the Android version.

**Comment by Ashoat** [comment]
Another thought: I wonder if we could make the transition from "ComposeThread" to "MessageList" cleaner if we actually used the same React Navigations screen for both.

Some implications:
1. The tab bar would stay visible, although this won't matter much since the keyboard will be in front of it
2. The default animation will be different from what we see in `Messenger`. Standard behavior will be to show the `MessageList` in the same way we normally do. We could consider a different style of animation if React Navigation supports it and we feel it looks better
3. The transition from "pending thread" to "real thread" should be more clean if we don't need to change React Navigation screens

@palys-swm, what do you think?

**Comment by palys-swm** [comment]
I'm not sure if I understand `if we actually used the same React Navigations screen for both` correctly. Do you mean, that we should have only one route (Chat.Screen MessageListRouteName) for both message list and thread composer, maybe with a param and based on that param we decide which thread to display and whether we should display a search component?
If that's correct, then the transition should be really smooth (as we only change the params). We can decide to always display message list as a "modal" (full width and height, but showing from the bottom and dismissible by down gesture). 
Regarding the tab bar, hiding it behind the keyboard is not a solution: it's possible for a device to have a physical keyboard. What we can do, is to hide the tab bar for a certain path / params. But we should think whether hiding the tab bar is really necessary.

I think that overall it might be a good idea: the experience should be improved.

**Comment by Ashoat** [comment]
> We can decide to always display message list as a "modal" (full width and height, but showing from the bottom and dismissible by down gesture)

For the standard `MessageList` animation (when we select a thread from the `ThreadList`) I think I would prefer to keep the current behavior.

The more I think about it, the more I wonder if having a modal animation even makes sense. We could keep the same behavior but just keep it as a standard `StackNavigator` card: showing from the right, and dismissable by swiping to the left. What do you think?

> Regarding the tab bar, hiding it behind the keyboard is not a solution: it's possible for a device to have a physical keyboard. What we can do, is to hide the tab bar for a certain path / params. But we should think whether hiding the tab bar is really necessary.

If we take the "standard `StackNavigator` card" approach, I think we could avoid worrying about the tab bar.

**Comment by palys-swm** [comment]
Agree, this is probably the simplest solution

**Comment by palys-swm** [comment]
> Hmm, displaying a list of matching threads seems like it will be challenging in terms of UX. At a higher level, our approach here should make it unlikely that there are multiple matching threads going forward, since the UI will make it impossible to create a second matching thread if one already exists. So if there are multiple matching threads, I think we can simply select the oldest one.
There will be an option for multiple matching threads to be created: whenever a user leaves (or joins) a thread, there's an opportunity for this thread to have the same set of users as one another. It might even happen that the thread was older than the original and would appear as a search result instead.

**Comment by Ashoat** [comment]
That makes sense. I think it's okay to accept that we'll autocomplete the older of the two threads in this edge case
