### ISSUE TITLE
Sidebar inline replies number

### ISSUE THREAD

**Issue by palys-swm** [CommE2E/comm#129]
Display a number of replies below the message which starts a sidebar

We have to be able to display this number to all the members of the parent thread (not necessarily members of the sidebar). To do that, we should create a new, invisible, message type which would modify inline sidebar. Initially this message should contain only number of replies.

1. Add a new message type (e.g. UPDATE_SIDEBAR). It should contain a number of replies and source message id.
2. Make sure that this message is completely invisible on the frontend
3. Write a spec of new message
    - it should not be persisted in db (just like unsupported message)
4. Modify thread info to contain a number of replies
5. Modify inline sidebar to display a number of replies based on thread info content
6. Modify the reducer to update thread's number of replies whenever UPDATE_SIDEBAR message is sent
7. Send current unread count when fetching sidebar
8. We should decide if we want the new message to generate a notification
9. Send update message when a new message is sent to the sidebar

**Comment by Ashoat** [comment]
1. Are you sure that the message shouldn't be persisted in the database? I think it will need to be, since that's the only way we can make sure that clients that are currently offline will get the message.
2. Worth noting that we'll need to do some additional thinking for E2E-encrypted "thick" threads. Probably best to handle in a separate issue, but we will need to consider that the contents of the sidebar won’t be visible unless we make sure that all members of the parent thread receive the encrypted messages in the sidebar.

**Comment by Ashoat** [comment]
I also don’t think we need to modify `ThreadInfo` for this. We should be able to handle this with something like `localThreadInfo` in `threadStore`.
